version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: lebenslauf
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
